/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCU_H_RPCGEN
#define _CALCU_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct dupla_int {
	int a;
	int b;
	char c;
};
typedef struct dupla_int dupla_int;

#define CALCU_PROG 0x23451111
#define CALCU_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALCU 1
extern  int * calcu_1(dupla_int *, CLIENT *);
extern  int * calcu_1_svc(dupla_int *, struct svc_req *);
extern int calcu_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALCU 1
extern  int * calcu_1();
extern  int * calcu_1_svc();
extern int calcu_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_dupla_int (XDR *, dupla_int*);

#else /* K&R C */
extern bool_t xdr_dupla_int ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCU_H_RPCGEN */
