/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcu.h"
#include <stdio.h>


void
calcu_prog_1(char *host, int a, int b, char c)
{
	CLIENT *clnt;
	int  *result_1;
	dupla_int  calcu_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCU_PROG, CALCU_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

calcu_1_arg.a=a;
calcu_1_arg.b=b;
calcu_1_arg.c=c;

	result_1 = calcu_1(&calcu_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("result = %d\n",*result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int a, b;
	char c;

	if (argc != 5) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	if ((a = atoi(argv[2])) == 0 && *argv[2] != '0'){
		fprintf(stderr, "invalid value:%s\n",argv[2]);
		exit (1);
	}

	if ((b = atoi(argv[3])) == 0 && *argv[3] != '0'){
		fprintf(stderr, "invalid value:%s\n",argv[3]);
		exit (1);
	}

	if ((c = *argv[4]) == 0 && *argv[4] != '0'){
		fprintf(stderr, "inavlid value:%s\n",argv[4]);
		exit (1);
	}
	calcu_prog_1 (host,a,b,c);
exit (0);
}
