/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcu.h"

int *
calcu_1_svc(dupla_int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	printf("El procedimiento ha sido invocado calculadora \n");
	printf("Server is working \n");
	printf("Parameters: %d, %d, %c\n",argp->a,argp->b,argp->c);
	if(argp->c == '+'){
		result = argp->a + argp->b;
	}
	else if(argp->c == '-'){
		result = argp->a - argp->b;
	}
	else if(argp->c == '*'){
		result = argp->a * argp->b;
	}
	else if(argp->c == '/'){
		result = argp->a / argp->b;
	}
	else{
		printf("Ponga un operador +,-,/,* \n");
		result = argp->c;
	}
	
	printf("returning: %d\n",result);

	return &result;
}
