/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "suma.h"

int *
suma_1_svc(dupla_int *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	printf("El procedimiento ha sido invocado remotamente\n"); //Paso 4
	printf("Server is working \n"); //Paso 11
	printf("parameters: %d, %d \n",argp->a, argp->b); //Paso 11
	result = argp->a + argp->b; //Paso 13
	printf("returning: %d\n",result); //Paso 13

	return &result; //Paso 11
}
